services:
  #  PostgreSQL database
  db:
    image: postgres:latest
    # The ports to expose to the host container
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: testtest!

  adminer:
      image: adminer:latest
      restart: always
      ports:
        - 8888:8080